### ISSUE TITLE
Warning in 1.0.1

### ISSUE THREAD

**Issue by cunhar** [hyperdefined/hyperMOTD#37]
I'm running 1.0.1 velocity and i get this in logs:

[15:57:31 WARN] [hypermotd]: A new version is available (1.0.1)! You are running version 1.0. You are 1 version(s) behind.

**Comment by hyperdefined** [comment]
I forgot to change the version on that one, you can ignore that for now.

**Comment by hyperdefined** [comment]
I didn't want to make a new release to fix it, so I just replaced the Velocity version here: https://github.com/hyperdefined/hyperMOTD/releases/tag/1.0.1

Just redownload it and replace the old one, the warning will be gone.

**Comment by cunhar** [comment]
thanks <3
